ungrouped:
  hosts:
    lisieux-automation.iac.lan:
    issoire-automation.iac.lan:
    lunel-testing.iac.lan:
webservers:
  hosts:
    lisieux-automation.iac.lan:
    issoire-automation.iac.lan:
    lunel-testing.iac.lan:
   
dbservers:
  hosts:
    lisieux-automation.iac.lan:
    issoire-automation.iac.lan:
    lunel-testing.iac.lan:

phpservers:
  hosts:  
    lisieux-automation.iac.lan:
    issoire-automation.iac.lan:
    lunel-testing.iac.lan:

nginx:
  hosts: 
    lunel-testing.iac.lan:
    lisieux-automation.iac.lan:
    issoire-automation.iac.lan:
